### ISSUE TITLE
Move to Heroku

### ISSUE THREAD

**Issue by rufuspollock** [rufuspollock-okfn/openletters#1]
Here's instructions for flask setup with yourtopia: https://github.com/okfn/yourtopia#deployment

For pylons setup also see: http://docs.pylonsproject.org/projects/pyramid_cookbook/en/latest/deployment/heroku.html

**Comment by rufuspollock** [comment]
@austgate ok, i've booted "opencorrespondence" app: http://opencorrespondence.herokuapp.com/

I've also added you as a collaborator. You'll now need to follow: https://github.com/okfn/yourtopia#to-deploy-already-created

**Comment by rufuspollock** [comment]
And aliased the domain ...

**Comment by rufuspollock** [comment]
@austgate any thoughts here - it would be lovely to get this up and running again. Other option is we run a core wordpress site and have data.opencorrespondence.org or api.opencorrespondence.org for the actual data side ...

**Comment by austgate** [comment]
@rgrp As per brief conversation have pushed the continuing rewrite to flask branch. Need to complete the places stuff and the html/css/js

**Comment by rufuspollock** [comment]
FIXED. http://opencorrespondence.org/
