### ISSUE TITLE
Put the data into timemapper

### ISSUE THREAD

**Issue by rufuspollock** [rufuspollock-okfn/openletters#10]
Get a nice timemap ...

http://timemapper.okfnlabs.org/

All we need is to convert data => csv => google docs spreadsheet

@austgate wdyt?

**Comment by austgate** [comment]
@rgrp I am happy with that :). Will do the conversion in the next couple of days if you want

**Comment by austgate** [comment]
If we just want the dates against person against a letter id, this exists in the data in the master branch. (metadata.csv). If we need other data in it, then this would need to be added.

**Comment by rufuspollock** [comment]
@austgate I really want a CSV file or similar with:
- date
- title
- description: (optional) - could be first paragraph or first few sentences of the letter
- place (in a form that can be geocoded)
- [optional but nice] location column with lon, lat (or separate lon, lat columns) (if not provided can probably geocode myself)
- source_url column with link to page for this letter on opencorrespondence

As an example here's what I managed to produce a couple of months ago from the XML (I think from https://github.com/okfn/openletters/blob/master/openletters/docs/dickens_letters.xml plus the place xml): https://docs.google.com/a/okfn.org/spreadsheet/ccc?key=0AqR8dXc6Ji4JdGROdFQ4S1JTTGFYX0twTFBhOHhhZFE&usp=drive_web#gid=0

This doesn't need to be in the repo - if you want to upload to gdocs or put elsewhere that is fine :-)

**Comment by rufuspollock** [comment]
@andylolz see above for the kind of info I need in a csv file or gdoc :-)

**Comment by austgate** [comment]
@rgrp Have put your CSV into a google doc and published to the web but timemapper seems to be hanging on it when publishing. I've made the spreadsheet public (and will work on updating it as and when) but just wanted to see what it looked like when publishing in timemapper. 

Update: no worries, think I've figured out what it is and dealing with it

**Comment by rufuspollock** [comment]
@austgate can you link to your item on timemapper - i or others can help debug :-)

**Comment by austgate** [comment]
http://timemapper.okfnlabs.org/iainemsley/open-correspondence

@rgrp: Published here. I've updated the spreadsheet to remove letters without the dates which I had assumed was the original problem but it is still hanging when loading (unless 800+ items takes a long while).

**Comment by austgate** [comment]
Now published. Thanks for the help @rgrp

**Comment by rufuspollock** [comment]
@austgate should we embed this on the front page or something?

Would this worth a blog post on okfnlabs.org?
